---
- name: Download Metricbeats .deb file
  command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
- name: Install Metricbeats
  command: dpkg -i metricbeat-7.6.1-amd64.deb
- name: Copy Metricbeats config file
  copy:
    src: /etc/ansible/files/metricbeat-configuration.yml
    dest: /etc/metricbeat/metricbeat.yml
- name: Enable metricbeat
  command: metricbeat modules enable docker
- name: Metricbeat setup
  command: metricbeat setup
- name: Start Metricbeat
  service:
    name: metricbeat
    state: started
