---
- name: Set Memory Size
  command: sysctl -w vm.max_map_count=262144
- name: docker.io
  apt:
    force_apt_get: yes
    name: docker.io
    state: present
- name: Install pip
  apt:
    force_apt_get: yes
    name: python-pip
    state: present
- name: Install Docker Python Module
  pip:
    name: docker
    state: present
- name: Download and Launch ELK Container
  docker_container:
    name: ELK
    image: sebp/elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
    state: started
